# Generated by Django 4.0.4 on 2022-05-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='device_vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ssh_user', models.CharField(max_length=256)),
                ('ssh_pwd', models.CharField(max_length=256)),
                ('ssh_port', models.IntegerField(default=22)),
                ('enab_pwd', models.CharField(blank=True, max_length=256)),
                ('snmp_ver', models.CharField(blank=True, choices=[('v1', 'v1'), ('v2c', 'v2c'), ('v3', 'v3')], max_length=256)),
                ('snmp_port', models.IntegerField(blank=True, default=161)),
                ('snmp_community', models.CharField(blank=True, max_length=256)),
                ('snmp_pwd', models.CharField(blank=True, max_length=256)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.device_types')),
                ('device_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.device_vendors')),
            ],
        ),
    ]
