# Generated by Django 4.0.4 on 2022-07-09 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='snmp_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='snmp_ver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.snmp_version'),
        ),
    ]
