# Generated by Django 4.2.3 on 2025-03-02 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_snmp_version_alter_masterdata_snmp_ver'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('device_type', 'Device Type'), ('device_vendor', 'Device Vendor'), ('snmp_version', 'SNMP Version')], max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='masterdata.lov'),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='device_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_vendors', to='masterdata.lov'),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='snmp_ver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_versions', to='masterdata.lov'),
        ),
        migrations.DeleteModel(
            name='device_types',
        ),
        migrations.DeleteModel(
            name='device_vendors',
        ),
        migrations.DeleteModel(
            name='snmp_version',
        ),
    ]
