# Generated by Django 4.0.4 on 2022-09-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_backupconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfig',
            name='b_file',
            field=models.FileField(max_length=255, upload_to='backup_config/'),
        ),
    ]
